### ISSUE TITLE
internimsclient also report remote users with group access

### ISSUE THREAD

**Issue by kevlarkevin** [scitran/api#10]
related to cni/nimsweb#66

internimsclient is to report on remote users with experiment (project) access, collection (virtual project) access, and group membership.

**Comment by kofalt** [comment]
Closing as I believe this to be obsolete.

**Comment by gsfr** [comment]
I don't think that remote group membership reporting ever got implemented, but we probably don't even want to allow that.

**Comment by kofalt** [comment]
Agreed, or at least we can tackle that when we discuss distributed authorization at length.
