### ISSUE TITLE
Bring back cron-like functionality

### ISSUE THREAD

**Issue by kofalt** [scitran/api#100]
At the moment, [job creation](https://github.com/scitran/api/blob/3d84ddf47a4c1a05bf2fd2bc7454ed8944904f94/bin/api.wsgi#L135-L189) only runs via uwsgi cron. Without uwsgi, these tasks will not run.

#93 will reduce but not eliminate our need for cron-like functionality. The current best proposal is to use [APScheduler](https://apscheduler.readthedocs.org/en/latest/), which has several advantages over our old approach and in general looks pretty great.

**Comment by gsfr** [comment]
@andynemzek is working on cron container in fly/fly.
