### ISSUE TITLE
Force flag not respected on file uploads

### ISSUE THREAD

**Issue by kofalt** [scitran/api#110]
Uploading redundant files are rejected with 409, even if the `force` flag is passed.
Expected behaviour is to overwrite the existing file and return 200.

To reproduce:

```bash
# Headers & settings
baseUrl="https://localhost:9000/api/projects"
alias sCurl="curl -sk -H 'User-Agent: SciTran Drone Engine' -H 'X-SciTran-Auth: change-me'"

# Get a project as an upload target
ProjectId=$(sCurl https://localhost:9000/api/projects | jq -r '.[0]._id')

# Generate a useless file
uname -a > example.bin

# Succeeds
sCurl $baseUrl/$ProjectId/files?force=true -F "file=@example.bin"

# Fails
sCurl $baseUrl/$ProjectId/files?force=true -F "file=@example.bin"
```

Example uses [jq](https://stedolan.github.io/jq), an excellent CLI tool for JSON manipulation.
Obviously, your instance will need at least one project for this to work.

**Comment by rentzso** [comment]
I think the behavior in aloha was to return a 202 return code without overriding the existing file. Is this correct?

**Comment by kofalt** [comment]
I'm not sure, though my understanding (via @gsfr) was that with the force flag set the server would overwrite the existing file and return 200. I'm pretty sure that was the previous behaviour.

**Comment by gsfr** [comment]
How about this?

Without *force*, the server returns a *409 Conflict*, if a file with the same name already exists.

With *force*, the server always accepts the file and returns *200 OK*. In case the new file is identical to the existing file, the server returns *202 Accepted* to indicate identity.

**Comment by kofalt** [comment]
Refresh my memory: Is our equivalence check now *only* the hash used for our storage CAS, or does it still open tar/zips and do CRC things? Because it [looks like the later](https://github.com/scitran/api/blob/06eb98aecdaa8836f6de9e6d0cd6f4acc6953018/api/files.py#L117-L132).

If it's the later, then I assert we don't actually have a valid equivalence check, for the reasons we've discussed before, and I would assert that we shouldn't have the `202 Accepted` behaviour and instead always accept & 200 if force is set.

If it's the former, then I agree wholeheartedly with your proposal :)
