### ISSUE TITLE
Generate URIs in a util module

### ISSUE THREAD

**Issue by kofalt** [scitran/api#130]
There have been several times where this jobs logic has had to change:

```
'/' + i['container_type'] + 's/' + i['container_id'] + '/files/' + i['filename']
```

That functionality really has nothing to do with jobs, and it's irritating having this be broken by unrelated code changes.

There should be functionality in a separate module that, at minimum, knows how to generate urls for uploading and downloading a file. The jobs module can then call that.

**Comment by rentzso** [comment]
postponed to when we have a client library
