### ISSUE TITLE
targeted uploads

### ISSUE THREAD

**Issue by gsfr** [scitran/api#14]
Add handling for targeted uploads (user or processor-specified container level and ID) to ```PUT /nimsdata```. Such uploads will come in as ```multipart/form-data``` and need to be differentiated from sortable uploads (such as those from the reaper), which carry no additional information.

**Comment by kofalt** [comment]
There are several commits that appear to reference this feature above - can this ticket be closed?

**Comment by gsfr** [comment]
Let's leave this open until the following functionality is in place:
```GET /.../file/<filename> + oauth token``` -> stream file
```GET /.../file/<filename>?ticket=``` -> download ticket request
```GET /.../file/<filename>?ticket=<ticket>``` -> download file
```GET /.../file/<filename>?ticket=<ticket>&view=true``` -> stream file
```POST /.../file/<filename>``` -> upload new file
```PUT /.../file/<filename>``` -> update metadata of file

@kofalt, @rentzso Does anything actually use the first GET variant?

**Comment by kofalt** [comment]
Not to my knowledge.

**Comment by rentzso** [comment]
no, even though we are using:
```GET /.../acquisitions/<acquisition_id>/tile?<coordinates> + oauth token``` -> download tiles

We may opt to use that GET variant instead

**Comment by gsfr** [comment]
Done.
