### ISSUE TITLE
API allows the deletion of "Unknown" group

### ISSUE THREAD

**Issue by ryansanford** [scitran/api#147]
@rentzso 
API should reject this request. The "unknown" group is integral and assumed to exist within the api, and needs protection. @gsfr recommended leaving the choice of the HTTP response code up to you.

This is required for bali milestone.

From chrome inspector:
```
Request URL:https://localhost:8443/api/groups/unknown?root=true
Request Method:DELETE
Status Code:200 OK
Remote Address:127.0.0.1:8443
```

**Comment by kofalt** [comment]
Good catch.
