### ISSUE TITLE
access control for file and attachment uploads

### ISSUE THREAD

**Issue by gsfr** [scitran/api#15]
No permissions checking is currently done for attachment uploads. Use ```Container._get()``` to do it:
```
self._get(_id, ‘rw’)
```
Also, file uploads currently require admin permission, but that should probably be changed to read-write as well.

**Comment by kofalt** [comment]
This looks like it can be closed - ref commits by @kevlarkevin that seem to add the feature mentioned.
Thoughts?

**Comment by gsfr** [comment]
Closed by 15cc166cb6b42f2cf55c161d02e5f5b092af204c.
