### ISSUE TITLE
Session Attachments JSON doesn't include file type.

### ISSUE THREAD

**Issue by mrDarcyMurphy** [scitran/api#151]
When fetching a project, the files array includes objects like this: 

```
{
  created: "2016-02-04T01:24:43.498000+00:00"
  hash: "v0-sha384-6d256b480d71816cb822f721e9cb36d28e7d0fd2b1005ef74ee2c89ea75dc5e9a46c3dc950659eb0a2e689fb02422bfd"
  modified: "2016-02-04T01:24:43.498000+00:00"
  name: "cookie.gif"
  size: 466272
  type: "gif"
}
```

When fetching a session, the files array includes objects like this:

```
{
  created: "2016-02-04T01:24:43.498000+00:00"
  hash: "v0-sha384-6d256b480d71816cb822f721e9cb36d28e7d0fd2b1005ef74ee2c89ea75dc5e9a46c3dc950659eb0a2e689fb02422bfd"
  modified: "2016-02-04T01:24:43.498000+00:00"
  name: "cookie.gif"
  size: 466272
}
```

Probably not critical for Bali, but would be nice to have soon.

**Comment by mrDarcyMurphy** [comment]
**Update:** I pulled the latest from the api this morning and projects are no longer including the file type either.

I'm able to compensate well enough on the front end, but it would be excellent if the file would return the mimetype in the object.

**Comment by kofalt** [comment]
Agreed. A larger issue is that

1) I don't like `type: "gif"` isn't a mime type
2) I don't like psuedo-mime-types conflated with scientific data types ("dicom")

I'll file a separate ticket to resolve the conflation.

**Comment by mrDarcyMurphy** [comment]
:+1:

**Comment by gsfr** [comment]
Looks like we are at least consistent. @mrDarcyMurphy, please close this in favor of #153 unless you need an immediate bali-critical resolution.
