### ISSUE TITLE
Q: module organization

### ISSUE THREAD

**Issue by Eric89GXL** [scitran/api#34]
I'm looking through the module, and it looks like the organization has some non-standard conventions, which is making it a little more challenging than usual for me to understand:

* imports are absolute (`import apps`) instead of relative (`from . import apps`) so it's tough to tell what is from the local package vs built-in or external imports
* scripts like `bootstrap.py` are in the same location as source modules -- typically these live in a `bin` directory or so, to make it clear what is part of the module, and what is a callable script

Do these need to be that way? I'm happy to work on reorganizing these aspects of package if it makes sense to do so at some point. I think it would make it easier to maintain and for other devs to understand the layout, and in the meantime would teach me a bit about the module. But if this seems overkill, it doesn't need to be done.

**Comment by gsfr** [comment]
Thank you. I think that would be great to have. It seems to make sense to do this before we take on scitran/scitran#2.

**Comment by Eric89GXL** [comment]
Hmm, now that I think about it, it might actually be easier to take care of this all at once as part of scitran/scitran#2 since it will require changing paths that the core bit of `scitran` needs.
