### ISSUE TITLE
Coalesce oAuth token requests

### ISSUE THREAD

**Issue by kofalt** [scitran/api#43]
Checking a new oauth token with the provider is [currently unconditional](https://github.com/scitran/api/blob/5b02572d351fcf3db688d0be22d27d21eee6345e/api/base.py#L41). This results in more upstream provider calls than are necessary if more than one API request occurs in a short interval with the new token.

Example: when our web app [receives a token error](https://github.com/scitran/api/blob/5b02572d351fcf3db688d0be22d27d21eee6345e/api/base.py#L68), we will contact Google for a new token, then re-make any failed requests to the scitran API. In practice, this is perhaps ~5 requests made simultaneously with the new token.

The API could coalesce oAuth token provider checks by sharing context between workers such that only one in-flight request for a given token occurs at a time. Expected result is making the correct & minimal request count on the oAuth provider.

**Comment by gsfr** [comment]
Thanks, @kofalt. How urgent is this? @josschne mentioned an issue with rate-limiting. As far as I know, we've never run into this with SDM. Pinging @rentzso confirmation/advice.

**Comment by kofalt** [comment]
I don't think it's very urgent, I mainly wanted to track it as an opportunity. I've been meaning to import GH labels from a successful OSS project I like, and if I had this would be tagged "p:low" :)

@josschne Hit Google's API limit during some testing, but I'm not currently convinced a site will be likely to hit that in production. OTOH, if this reduces upstream oAuth provider calls by a factor of ~5, which seems likely, it's definitely something we should do sooner or later.

**Comment by josschne** [comment]
Definitely saw a rate limit error from Google, but it was while testing with invalid oauth tokens (part of how I was testing a refresh scenario without having to wait an hour). Basically if an app hits the API with a bunch of requests with a new/refreshed token, there is a window during which each of them will result in a separate request out to Google. Agree with @kofalt and @gsfr that this is a good idea, but low priority.

**Comment by rentzso** [comment]
@gsfr we never noticed this issue before, but it may be possible that the retry logic on SDM has masked the problem. Is there any retry logic on FDM's API calls? Probably it is not a good long-term solution, but it could be a convenient work-around.

**Comment by kofalt** [comment]
Our client logic is slightly sub-optimal ATM: if a request fails due to invalid token, we get a new token and retry the request. This results in the web app, for example, renewing a token 5 times and sending 5 requests each with a different (new, valid) token. 

Ideally, when a token renewal is in-flight, all failed / new requests would hold for that, then all use the same token. Once that client-side bug is fixed, we'd still have the *server* making redundant requests, which this ticket will address.

**Comment by gsfr** [comment]
Sounds good. Let's draft a solution by the end of the week.

**Comment by gsfr** [comment]
@josschne believes that hello.js is already handling token reveal correctly and only retrieving a single new token.

**Comment by kofalt** [comment]
Cool; that leaves only this ticket to resolve then if I understand correctly

**Comment by gsfr** [comment]
As I stated in #44, this may not a actually be an issue that needs resolving right now. The app *should* never be sending concurrent requests with non-cached tokens. @josschne is working on ensuring that ```/users/self``` requests always happen *before* further, concurrent requests. Let's see where that leaves us and then reprioritize as needed.

@kofalt If you have thoughts on a possible implementation of this enhancement, please document them here.

**Comment by rentzso** [comment]
closed after discussion with @kofalt
