### ISSUE TITLE
Dev infrastructure

### ISSUE THREAD

**Issue by gsfr** [scitran/api#60]
We are looking to create a simple, yet effective way to launch the scitran API for developers. Besides the API itself, the only other launch requirement is ```mongod```. A single entry point, such as ```./scitran.sh run``` and a single config file are desired. Ideally, no further dependencies are introduced. Implementation candidates are bash and python. Options for app launching and live reloading are [Reflex](https://github.com/cespare/reflex) and possibly [Paste Script](http://pythonpaste.org/script/).

Below is a starting point for discussion, intended to be refined in place before commencing work.

Requirements:
- [ ] works on
  - [x] Mac
  - [ ] Linux
  - [ ] Linux in Vagrant on Mac
- [x] live reloading of the API
- [x] API's stdout and stderr are printed
- [x] bootstrapping of users and data from arbitrary locations

Targets:
- [ ] ```prepare``` - recent bash may be all we need
- [ ] ```run``` - ```setup``` + ```bootstrap``` + ```launch```
- [ ] ```setup``` - install reflex, mongo, venv, etc.
- [ ] ```launch``` - launch API and mongo
- [ ] ```update``` - update this repo
- [ ] ```cmd``` - run arbitrary commands in the application context

Convenience targets (likely wrappers around ```cmd```):
- [ ] ```bootstrap``` - bootstrap users or data
- [ ] ```reset``` - reset database (via ```boostrap.py clean```)
- [ ] ```mongo-log``` - tail the ```mongod``` log
- [ ] ```python``` - ipython shell with ```db``` variable set
- [ ] ```lint``` - run a linter

Directory structure:
- ```scitran.sh``` or ```scitran.py``` - entry point
- ```api``` - API source code
- ```bin``` - ```api.wsgi``` and ```bootstrap.py```
- ```test``` - unit and integration tests
- ```runtime``` - disposable environment for python dependencies and mongo binaries
- ```templates``` - ```bootstrap.json```, ```config.toml```
- ```persistent``` - ```data```, ```db```

**Comment by Eric89GXL** [comment]
Is this related to https://github.com/scitran/scitran/issues/2, or is it specific to the `api` repo?

**Comment by kofalt** [comment]
This should probably moved to scitran/scitran.

**Comment by gsfr** [comment]
This is specific to the API and should thus stay here. We may still rename this repo to ```core``` if that makes more sense.

The API is about to shed its scitran/data dependency, at which point it will be datatype-agnostic and no longer have dependencies on other scitran components.

The reaper is a separate tool and often runs on separate hardware. (Also working on [dropping](https://github.com/scitran/reaper/tree/multipart) its scitran/data dependency, btw. @Eric89GXL Looks like the meeg reaper is already good on that front, but other updates will be necessary to send [newly-required sorting metadata](https://github.com/scitran/reaper/blob/multipart/scitran/reaper/reaper.py#L30-L57) to the API.)

scitran/data probably needs redesign to be less monolithic. @lmperry You are the apps master, so glancing in your direction for guidance on this.

Getting back to this ticket, we may have a broader version of this in scitran/scitran that might also spin up other components, which may include scitran/sdm and scitran/engine, although we are not sure about supporting SDM much longer and the open source engine has been defunct for months. Alternatively, scitran/scitran might also just go away.

@andynemzek will be working on a much more comprehensive version of this, albeit under the [Flywheel](https://flywheel.io) umbrella, likely closed source.

**Comment by gsfr** [comment]
So, this is mostly done, although it was done differently from what is described above. No targets have been created, but rather an environment variable-based config system has been put in place. `./bin/run.sh` is all you need.

Unfortunately, it works only on Mac, using Homebrew, which is good for many developers, but having Linux support, too, would be great. Closing this ticket now. Tentatively hoping for a contribution from @constellates to add Linux support in a separate PR.
