### ISSUE TITLE
Eliminate or harmonize upload digest

### ISSUE THREAD

**Issue by kofalt** [scitran/api#64]
[SSL already provides integrity](https://en.wikipedia.org/wiki/Transport_Layer_Security#Data_integrity); all modern clients will most likely use HMAC-SHA256 at the transport level.

In order of desire:

1. Eliminate obsolete digest options (MD5)
2. If we're going to have an upload digest, harmonize with CAS storage
3. Make upload digest optional (may already be the case), or eliminate entirely

Tagging @ryansanford he probably has the most experience in this area.

**Comment by gsfr** [comment]
Thanks for the reference, @kofalt. @rentzso and I have started the removal process. The reaper is already clean, for instance.

Leaving open, pending further comments from @ryansanford.

**Comment by kofalt** [comment]
Notably, the transport between the SSL terminator (nginx) and the endpoint (uwsgi) has to also provide integrity. Right now that's trivially the case since both are on the same box.

If for some reason we chose to do SSL termination on a separate box, and don't trust the deployment's intranet, this becomes an issue again - but a larger issue than upload corruption; in that scenario any interaction could experience corruption.

**Comment by gsfr** [comment]
Closing for now...

**Comment by kofalt** [comment]
Is this tackled by #67?

**Comment by rentzso** [comment]
yes, we have changed the code that computes the hashes deciding to drop support for MD5
