### ISSUE TITLE
Uploading data doesn't result in jobs getting created in master branch

### ISSUE THREAD

**Issue by ryansanford** [scitran/api#83]
Looks like this was caused by renaming some elements of the file document inside the acquisitions collection within mongodb.

dirty->unprocessed
filename->name
filehash->hash
filetype->type

One example of the mismatch
api.wsgi Line 136
            for c in application.db[c_type].find({'files.dirty': True}, ['files']):

**Comment by ryansanford** [comment]
@gsfr 
@rentzso

**Comment by kofalt** [comment]
Renamed to make it clear that *any* uploaded file will currently fail to spawn a job.
