### ISSUE TITLE
Script organization

### ISSUE THREAD

**Issue by josschne** [scitran/api#96]
Determine new location/home for /run.sh and /bin/* files. /scripts could be a place to do this.

**Comment by kofalt** [comment]
Interested in what @andynemzek thinks?

**Comment by andynemzek** [comment]
We talked.  This has more to do with where we want to store scripts.  I don't have many opinions about where to put run.sh other than it's convenient to have it at root.

**Comment by josschne** [comment]
Last change that merged renamed the dir to bin/. Open to change it.

**Comment by gsfr** [comment]
Sounds like we are all in agreement on `/bin`. I'll make that change as part of my ongoing config/env var restructuring.
