### ISSUE TITLE
Change convention of API parameters to override config.toml with passed parameters.

### ISSUE THREAD

**Issue by ryansanford** [scitran/api#98]
Currently the config .toml file is used as the source of truth. Reverse the convention to be more intuitive.

This impacts api.wsgi today, and bootstrap.py soon.

**Comment by gsfr** [comment]
There is a plan in place to remove all command line parameters. The API will read it's entire configuration from environment variables. Those are either supplied via `run.sh` from a config file or via docker compose. Would that work for you, @ryansanford? Comments welcome.

**Comment by ryansanford** [comment]
Ok, closing.... Source of truth for the API will be environment variables. I can proceed with the docker input path without changing bootstrap.py. Eventually when your change lands, I'll need to make a small change to the docker input path to allign the var names with your change.

@andynemzek  or yourself will make sure the config.toml input path aligns with your change.

Closing this issue, since the above makes this concern obsolete.
